[project]
name = "kairos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dar-rius", email = "mohamedtine17@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["kairos"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
